---
# - name: Deploy Docker Compose Stack
#   listen: "restart app"
#   command: /usr/local/bin/docker-compose -f /home/centos/app/docker-compose.yml -f /home/centos/app/docker-compose.{{ deploy_env }}.yml up -d --force-recreate
#   become: true

- name: Deploy Docker Compose Stack
  listen: "restart app"
  command: /usr/local/bin/docker-compose -f /home/centos/app/docker-compose.{{ deploy_env }}.yml up -d --force-recreate
  become: true
