---
# handlers file for deploy-app
- name: Restart and Pull Docker Image
  listen: "restart app"
  command: >
    /usr/local/bin/docker-compose -f /home/centos/app/docker-compose.yml up -d --force-recreate
  become: true
