name: CD - Deploy to EC2

on:
  push:
    branches:
      - chore/*

jobs:
  tag-release:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: payoneer

    outputs:
      tag: ${{ steps.tag_version.outputs.tag }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Current Version
        id: version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Create and Push Tag
        id: tag_version
        run: |
          TAG="${{ env.VERSION }}-${{ github.run_number }}"
          echo "New Tag: $TAG"
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag $TAG
          git push origin $TAG
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "tag=$TAG" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: payoneer

    needs: tag-release
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          echo "Using tag: ${{ needs.tag-release.outputs.tag }}"
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/payoneer-app:${{ needs.tag-release.outputs.tag }} .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/payoneer-app:${{ needs.tag-release.outputs.tag }}

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook for Deployment
        uses: jawher/action-ansible@2.9.7
        env:
           ANSIBLE_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          args: ansible-playbook ../.infra/ansible/deployment.yml -i ${{ secrets.EC2_HOST }}, -u ${{ secrets.EC2_USER }} -e ec2_host_name=${{ secrets.EC2_HOST }}  -e "docker_image_tag=${{ needs.tag-release.outputs.tag }}"  -e "docker_hub_username=${{ secrets.DOCKER_HUB_USERNAME }}"

#      - name: Run Ansible Playbook for Deployment
#        uses: dawidd6/action-ansible-playbook@v3
#        with:
#          playbook: deployment.yml
#          directory: .infra/ansible
#          key: ~/.ssh/id_rsa
#          inventory: |
#            [web]
#            ${{ secrets.EC2_HOST }} ansible_ssh_user=centos ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_python_interpreter=/usr/bin/python
#          options: |
#            -e "docker_image_tag=${{ needs.tag-release.outputs.tag }}"
#            -e "ec2_host_name=${{ secrets.EC2_HOST }}"
#            -e "docker_hub_username=${{ secrets.DOCKER_HUB_USERNAME }}"
