name: CD - Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Current Version
        id: version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Create and Push Tag
        run: |
          TAG="${{ env.VERSION }}-${{ github.run_number }}"
          echo "New Tag: $TAG"
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git tag $TAG
          git push origin $TAG
          echo "TAG=$TAG" >> $GITHUB_ENV

  deploy:
    runs-on: ubuntu-latest
    needs: tag-release
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/payoneer-app:${{ env.TAG }} .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/payoneer-app:${{ env.TAG }}

      - name: Run Ansible Playbook for Deployment
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deployment.yml
          directory: .infra/ansible
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: |
            [web]
            ${{ secrets.EC2_HOST }}
          options: |
            -e "docker_image_tag=${{ env.TAG }}"
            -e "ec2_host_name=${{ secrets.EC2_HOST }}"
            -e "docker_hub_username=${{ secrets.DOCKER_HUB_USERNAME }}"
