name: Deploy Docker with Ansible

on:
  push:
    branches:
      - main
    path:
      - '.infra/ansible/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: install_docker.yml
          directory: ./.infra/ansible
          inventory: inventory.ini
          key: ${{ secrets.SSH_PRIVATE_KEY }}
